// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TradeDeskTop/protos/servicecontract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ServiceContract {
  /// <summary>
  /// Trade service definition.
  /// </summary>
  public static partial class TradeServiceStreamer
  {
    static readonly string __ServiceName = "ServiceContract.TradeServiceStreamer";

    static readonly grpc::Marshaller<global::ServiceContract.TradeRequest> __Marshaller_ServiceContract_TradeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServiceContract.TradeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServiceContract.TradeDataContract> __Marshaller_ServiceContract_TradeDataContract = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServiceContract.TradeDataContract.Parser.ParseFrom);

    static readonly grpc::Method<global::ServiceContract.TradeRequest, global::ServiceContract.TradeDataContract> __Method_GetAllTrades = new grpc::Method<global::ServiceContract.TradeRequest, global::ServiceContract.TradeDataContract>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAllTrades",
        __Marshaller_ServiceContract_TradeRequest,
        __Marshaller_ServiceContract_TradeDataContract);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ServiceContract.ServicecontractReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TradeServiceStreamer</summary>
    [grpc::BindServiceMethod(typeof(TradeServiceStreamer), "BindService")]
    public abstract partial class TradeServiceStreamerBase
    {
      public virtual global::System.Threading.Tasks.Task GetAllTrades(global::ServiceContract.TradeRequest request, grpc::IServerStreamWriter<global::ServiceContract.TradeDataContract> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TradeServiceStreamer</summary>
    public partial class TradeServiceStreamerClient : grpc::ClientBase<TradeServiceStreamerClient>
    {
      /// <summary>Creates a new client for TradeServiceStreamer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TradeServiceStreamerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TradeServiceStreamer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TradeServiceStreamerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TradeServiceStreamerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TradeServiceStreamerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::ServiceContract.TradeDataContract> GetAllTrades(global::ServiceContract.TradeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllTrades(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::ServiceContract.TradeDataContract> GetAllTrades(global::ServiceContract.TradeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAllTrades, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TradeServiceStreamerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TradeServiceStreamerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TradeServiceStreamerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllTrades, serviceImpl.GetAllTrades).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TradeServiceStreamerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllTrades, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::ServiceContract.TradeRequest, global::ServiceContract.TradeDataContract>(serviceImpl.GetAllTrades));
    }

  }
}
#endregion
